# Generated by Django 3.2.9 on 2021-12-11 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncaoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('salarioBase', models.FloatField()),
            ],
            options={
                'db_table': 'funcaoFuncionario',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cnh',
            field=models.IntegerField(default=13579, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locacao',
            name='acressimos',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='locacao',
            name='valor',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(choices=[('PRETO', 'Preto'), ('BRANCO', 'Branco'), ('PRATA', 'Prata'), ('VERMELHO', 'Vermelho'), ('CINZA', 'Cinza'), ('AZUL', 'Azul'), ('AMARELO', 'Amarelo'), ('VERDE', 'Verde'), ('LARANJA', 'Laranja'), ('OUTRA', 'Outra')], max_length=10),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('INDISPONIVEL', 'Indisponível'), ('EM_AVALIACAO', 'Devolvido - Em Avaliação'), ('CONSERTO', 'Devolvido - Conserto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tipo',
            field=models.CharField(choices=[('CUPE', 'Cupe'), ('CROSSOVER', 'Crossover'), ('ESPORTIVO', 'Esportivo'), ('HATCH', 'Hacth'), ('JIPE', 'Jipe'), ('PICAPE', 'Picape'), ('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('VAN/MINIVAM', 'Van/Minivam')], max_length=15),
        ),
        migrations.CreateModel(
            name='JustificativaReprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locadora.cliente')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locadora.funcionarios')),
            ],
            options={
                'db_table': 'justificativa',
            },
        ),
        migrations.CreateModel(
            name='Aquisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=200)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locadora.fornecedor')),
            ],
            options={
                'db_table': 'aquisicao',
            },
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='funcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locadora.funcaofuncionario'),
        ),
    ]
