# Generated by Django 3.2.9 on 2021-12-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='preco',
            field=models.FloatField(default=100.0),
            preserve_default=False,
        ),
    ]
