# Generated by Django 3.2.9 on 2021-11-21 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
        migrations.AlterModelTable(
            name='funcionario',
            table='funcionario',
        ),
    ]
