# Generated by Django 3.2.9 on 2021-11-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0002_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='funcao',
        ),
    ]
