# Generated by Django 3.2.9 on 2021-12-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0002_auto_20211211_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='data_prevista_devolucao',
            field=models.DateField(default='2021-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='combustivel',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='quilometragem',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locacao',
            name='status',
            field=models.CharField(choices=[('RESERVA', 'Reserva'), ('EM_ABERTO', 'Em Aberto'), ('EM_AVALIACAO', 'Em Avaliacao'), ('FECHADA', 'Fechada')], max_length=15),
        ),
    ]
