# Generated by Django 3.2.9 on 2021-11-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0003_remove_cliente_funcao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=200)),
                ('cor', models.CharField(max_length=15)),
                ('ano', models.IntegerField()),
                ('placa', models.CharField(max_length=15)),
                ('tipo', models.CharField(choices=[('CUPE', 'Cupe'), ('CROSSOVER', 'Crossover'), ('ESPORTIVO', 'Esportivo'), ('HATCH', 'Hacth'), ('JIPE', 'Jipe'), ('PICAPE', 'Picape'), ('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('VAN E MINIVAM', 'Van/Minivam')], max_length=15)),
                ('status', models.CharField(choices=[('DISPONÍVEL', 'Disponível'), ('INDISPONÍVEL', 'Indisponível')], max_length=20)),
            ],
            options={
                'db_table': 'veiculo',
            },
        ),
    ]
