# Generated by Django 3.2.9 on 2021-11-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0004_veiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=90)),
                ('telefone', models.IntegerField()),
                ('email', models.CharField(max_length=60)),
                ('produto', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'fornecedor',
            },
        ),
    ]
