# Generated by Django 3.2.9 on 2021-11-21 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0005_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_locacao', models.DateField()),
                ('data_devolucao', models.DateField()),
                ('status', models.CharField(choices=[('EM_ABERTO', 'Em Aberto'), ('FECHADA', 'Fechada')], max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locadora.cliente')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locadora.funcionarios')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locadora.veiculo')),
            ],
            options={
                'db_table': 'locacao',
            },
        ),
    ]
