# Generated by Django 3.2.9 on 2021-12-12 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0005_auto_20211212_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locacao',
            name='owner',
        ),
        migrations.AlterField(
            model_name='locacao',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locadora.funcionarios'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='valor',
            field=models.FloatField(default=0),
        ),
    ]
