# Generated by Django 3.2.9 on 2021-12-19 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locadora', '0006_auto_20211212_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquisicao',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='locadora.fornecedor'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='funcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='locadora.funcaofuncionario'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='justificativareprovacao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='locadora.cliente'),
        ),
        migrations.AlterField(
            model_name='justificativareprovacao',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='locadora.funcionarios'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='locadora.cliente'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='locadora.funcionarios'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='locadora.veiculo'),
        ),
    ]
