# Generated by Django 3.2.9 on 2021-12-14 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0002_locacao_preco'),
        ('locadora', '0006_auto_20211212_1955'),
    ]

    operations = [
    ]
